// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwSGUZpKYVSPCF7xlKniZagoyD-D_SU4',
    appId: '1:353390083351:web:82cce759c101f755654b52',
    messagingSenderId: '353390083351',
    projectId: 'bison-garage',
    authDomain: 'bison-garage.firebaseapp.com',
    storageBucket: 'bison-garage.firebasestorage.app',
    measurementId: 'G-D6QB103G0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf0gshBTy9PGABSp9s23uw3s437rxzuEY',
    appId: '1:353390083351:android:d3b08aa86806f875654b52',
    messagingSenderId: '353390083351',
    projectId: 'bison-garage',
    storageBucket: 'bison-garage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb92AGq_flL29zhZexvudOpQU8KWBBAZs',
    appId: '1:353390083351:ios:b55a5e21442d8d7e654b52',
    messagingSenderId: '353390083351',
    projectId: 'bison-garage',
    storageBucket: 'bison-garage.firebasestorage.app',
    iosBundleId: 'com.example.bisonGarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb92AGq_flL29zhZexvudOpQU8KWBBAZs',
    appId: '1:353390083351:ios:b55a5e21442d8d7e654b52',
    messagingSenderId: '353390083351',
    projectId: 'bison-garage',
    storageBucket: 'bison-garage.firebasestorage.app',
    iosBundleId: 'com.example.bisonGarage',
  );
}
